const app=document.getElementById('app');let currentUser=null,currentPage='home',currentGame=null,currentTab='Game Lines',slip=[];let loginStage='select';let pendingUser=null;let pendingPin='';
function qs(s){return document.querySelector(s)}function saveState(){localStorage.setItem('msb_locked_final_v2',JSON.stringify(STATE))}function loadState(){const raw=localStorage.getItem('msb_locked_final_v2');if(raw){try{Object.assign(STATE,JSON.parse(raw))}catch(e){}}}loadState();

function renderLogin(){
  let inner='';
  if(loginStage==='select'){
    inner=`<div class='sectionTitle'>Choose Your Name</div><div class='small'>Pick your user first, then create or confirm your PIN.</div>
    <label class='small' style='display:block;margin-top:14px'>User<select id='loginUser'>${STATE.users.map(u=>`<option value='${u.name}'>${u.name}</option>`).join('')}</select></label>
    <button class='primary' id='nextUserBtn' style='margin-top:14px;width:100%'>Continue</button>`;
  } else if(loginStage==='create'){
    inner=`<div class='sectionTitle'>Create PIN</div><div class='small'>${pendingUser.name}, enter your 4-digit PIN.</div>
    <input id='createPin' type='password' inputmode='numeric' maxlength='4' placeholder='Create 4-digit PIN'>
    <div class='flex' style='margin-top:12px'><button class='ghost' id='backToUser'>Back</button><button class='primary' id='createPinBtn' style='flex:1'>Continue</button></div>`;
  } else if(loginStage==='confirm'){
    inner=`<div class='sectionTitle'>Confirm PIN</div><div class='small'>Re-enter your 4-digit PIN for ${pendingUser.name}.</div>
    <input id='confirmPin' type='password' inputmode='numeric' maxlength='4' placeholder='Confirm 4-digit PIN'>
    <div class='flex' style='margin-top:12px'><button class='ghost' id='backToCreate'>Back</button><button class='primary' id='confirmPinBtn' style='flex:1'>Login</button></div>`;
  }
  app.innerHTML=`<div class='header'><div class='h1'>${STATE.title}</div><div class='sub'>${STATE.subtitle}</div></div><div class='wrap'><div class='loginCard'>${inner}</div></div>`;
  if(loginStage==='select'){
    qs('#nextUserBtn').onclick=()=>{pendingUser=STATE.users.find(u=>u.name===qs('#loginUser').value);loginStage='create';renderLogin();};
  }
  if(loginStage==='create'){
    qs('#backToUser').onclick=()=>{loginStage='select';pendingUser=null;pendingPin='';renderLogin();};
    qs('#createPinBtn').onclick=()=>{const p=qs('#createPin').value.trim();if(!/^\d{4}$/.test(p)){alert('Enter a 4-digit PIN');return;}pendingPin=p;loginStage='confirm';renderLogin();};
  }
  if(loginStage==='confirm'){
    qs('#backToCreate').onclick=()=>{loginStage='create';renderLogin();};
    qs('#confirmPinBtn').onclick=()=>{const p=qs('#confirmPin').value.trim();if(p!==pendingPin){alert('PINs do not match');return;}pendingUser.pin=p;currentUser=pendingUser;pendingUser=null;pendingPin='';loginStage='select';saveState();renderApp();};
  }
}
function selectedClass(label){return slip.some(s=>s.label===label)?'selected':''}
function toggleSlip(label,odds){const i=slip.findIndex(s=>s.label===label);if(i>=0)slip.splice(i,1);else slip.push({label,odds});renderApp();}
function slipOddsDisplay(){if(slip.length<2)return'Need at least 2 legs';return '+'+(100+slip.length*125)}
function renderHeader(){return `<div class='header'><div class='h1'>${STATE.title}</div><div class='sub'>${STATE.subtitle} • Week ${STATE.week}</div></div>`}
function oddsCell(label,main,sub){return `<button class='oddsBtn ${selectedClass(label)}' onclick='toggleSlip(${JSON.stringify(label)},${JSON.stringify(sub||main)})'><span class='oddsMain'>${main}</span>${sub?`<span class='oddsSub'>${sub}</span>`:''}</button>`}
function renderHome(){return `<div class='wrap'><div class='card'><div class='sectionTitle'>Welcome, ${currentUser.name}</div><div class='small'>Available Bankroll: <strong>$${currentUser.available}</strong></div></div>${STATE.games.map(g=>`<div class='boardCard'><div class='gameTheme' style='background:linear-gradient(90deg,${g.theme[0]},${g.theme[1]})'></div><div class='boardTop'><div><div class='matchup'><img src='${g.awayLogo}' alt=''><span>${g.title}</span></div><div class='userTag'>${g.userLabel}</div></div><button class='ghost' onclick="openGame('${g.id}')">Open</button></div><div class='marketGrid'><div></div><div class='marketHdr'>Spread</div><div class='marketHdr'>Moneyline</div><div class='marketHdr'>Total</div><div class='teamCell'><img src='${g.awayLogo}' alt=''><span>${g.away}</span></div>${oddsCell(g.away+' '+g.board.away.spread,g.board.away.spread,g.board.away.spreadOdds)}${oddsCell(g.away+' ML '+g.board.away.ml,g.board.away.ml,'')}${oddsCell(g.away+' '+g.board.away.total,g.board.away.total,g.board.away.totalOdds)}<div class='teamCell'><img src='${g.homeLogo}' alt=''><span>${g.home}</span></div>${oddsCell(g.home+' '+g.board.home.spread,g.board.home.spread,g.board.home.spreadOdds)}${oddsCell(g.home+' ML '+g.board.home.ml,g.board.home.ml,'')}${oddsCell(g.home+' '+g.board.home.total,g.board.home.total,g.board.home.totalOdds)}</div></div>`).join('')}</div>`}
function openGame(id){currentGame=STATE.games.find(g=>g.id===id);currentTab='Game Lines';currentPage='game';renderApp();}
function renderGame(){const g=currentGame;return `<div class='wrap'><div class='card'><div class='flex' style='justify-content:space-between'><button class='ghost' onclick="currentPage='home';renderApp()">← Back</button><div class='small'>${g.title}</div></div><div class='sectionTitle' style='margin-top:10px'>${g.title}</div><div class='userTag'>${g.userLabel}</div><div class='tabBar'>${Object.keys(g.tabs).map(tab=>`<button class='${tab===currentTab?'active':''}' onclick="currentTab='${tab}';renderApp()">${tab}</button>`).join('')}</div>${(g.tabs[currentTab]||[]).map(item=>`<div class='leg'><div>${item[0]}</div><button class='oddsBtn ${selectedClass(item[0]+' '+item[1])}' style='min-width:100px' onclick='toggleSlip(${JSON.stringify(item[0]+' '+item[1])},${JSON.stringify(item[1])})'><span class='oddsMain'>${item[1]}</span></button></div>`).join('')}</div></div>`}
function renderMyBets(){const mine=STATE.bets.filter(b=>b.user===currentUser.name);return `<div class='wrap'><div class='card'><div class='sectionTitle'>My Bets</div><div class='small'>Clean ticket cards.</div></div>${mine.map(b=>`<div class='ticket'><div class='ticketTop'><div><div style='font-weight:900;font-size:20px'>${b.id}</div><div class='small'>${b.week} • ${b.type}</div></div><div class='badge OPEN'>${b.status}</div></div><div class='small' style='margin-top:8px'>Odds: ${b.odds} • Stake: $${b.stake} • Potential Win: ${b.payout}</div><ul class='legsList'>${b.legs.map(l=>`<li>${l}</li>`).join('')}</ul></div>`).join('')}</div>`}
function renderBankroll(){return `<div class='wrap'><div class='card'><div class='sectionTitle'>Full League Bankroll</div><table class='bankTable'><thead><tr><th>User</th><th>Start</th><th>Wagered</th><th>Available</th><th>Open Bets</th></tr></thead><tbody>${STATE.users.map(u=>`<tr><td>${u.name}</td><td>$${u.start}</td><td>$${u.wagered}</td><td>$${u.available}</td><td>${u.openBets}</td></tr>`).join('')}</tbody></table></div></div>`}
function applyAdminCommand(){if(!currentUser?.isAdmin){alert('Admin only');return;}const raw=qs('#adminCode').value.trim();if(!raw){alert('Paste a command JSON first');return;}try{const cmd=JSON.parse(raw);if(cmd.type==='setBankroll'&&cmd.user){const u=STATE.users.find(x=>x.name===cmd.user);if(u){if(cmd.available!==undefined)u.available=Number(cmd.available);if(cmd.wagered!==undefined)u.wagered=Number(cmd.wagered);if(cmd.openBets!==undefined)u.openBets=Number(cmd.openBets);}}if(cmd.type==='addBet'&&cmd.bet){STATE.bets.unshift(cmd.bet)}if(cmd.type==='setWeek'&&cmd.week!==undefined){STATE.week=Number(cmd.week)}if(cmd.type==='replaceGames'&&Array.isArray(cmd.games)){STATE.games=cmd.games}if(cmd.type==='mergeState'&&cmd.state&&typeof cmd.state==='object'){Object.assign(STATE,cmd.state)}saveState();alert('Command applied');renderApp();}catch(e){alert('Bad JSON command')}}
function fillExample(which){let obj={};if(which==='bank')obj={type:'setBankroll',user:'Tuane',available:1300,wagered:100,openBets:1};if(which==='bet')obj={type:'addBet',bet:{id:'BET-007',user:'Tuane',week:4,type:'Parlay',status:'OPEN',stake:50,odds:'+380',payout:'$240.00',legs:['Trevor Lawrence Over 274.5 Passing Yards','DK Metcalf Anytime TD']}};if(which==='week')obj={type:'setWeek',week:5};qs('#adminCode').value=JSON.stringify(obj,null,2)}
function exportState(){const blob=new Blob([JSON.stringify(STATE,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='madden-sportsbook-state.json';a.click();}
function renderAdmin(){if(!currentUser.isAdmin){return ''}return `<div class='wrap'><div class='card'><div class='sectionTitle'>Admin Command Center</div><div class='small'>Paste JSON commands here to update bankrolls, bets, week, or replace games without touching code files.</div><textarea id='adminCode' class='codeBox' placeholder='{"type":"setBankroll","user":"Tuane","available":1300}'></textarea><div class='flex' style='margin-top:10px;flex-wrap:wrap'><button class='primary' onclick='applyAdminCommand()'>Apply Command</button><button class='mini' onclick="fillExample('bank')">Bankroll Example</button><button class='mini' onclick="fillExample('bet')">Add Bet Example</button><button class='mini' onclick="fillExample('week')">Week Example</button><button class='ghost' onclick='exportState()'>Export State</button></div><div class='helper small'><strong>Supported commands</strong><br>setBankroll • addBet • setWeek • replaceGames • mergeState</div></div></div>`}
function renderSlip(){if(!slip.length)return '';return `<div class='betSlip'><div class='flex' style='justify-content:space-between'><div style='font-weight:900'>Bet Slip (${slip.length})</div><button class='ghost' onclick='slip=[];renderApp()'>Clear</button></div>${slip.map(s=>`<div class='betSlipItem'>${s.label}</div>`).join('')}<div style='margin-top:12px' class='small'>Parlay Odds: <strong>${slipOddsDisplay()}</strong></div><input id='stake' type='number' min='25' max='150' placeholder='Stake (min $25)'><div class='small' style='margin-top:8px'>Min 2 legs • Max 5 weekly • Max $150 per parlay</div><button class='primary' style='width:100%;margin-top:10px' onclick='placeBet()'>Place Bet</button></div>`}
function placeBet(){if(slip.length<2){alert('Minimum 2 legs');return;}const stake=Number(qs('#stake')?.value||0);if(stake<25){alert('Minimum stake is $25');return;}if(stake>150){alert('Max per parlay is $150');return;}alert('Bet placed. You can track it in My Bets.');slip=[];renderApp()}
function renderNav(){const items=[['home','Home'],['game','Games'],['bets','My Bets'],['bank','Bankroll']];if(currentUser&&currentUser.isAdmin){items.push(['admin','Admin'])}return `<div class='bottomNav'>${items.map(([key,label])=>`<button class='navBtn ${currentPage===key?'active':''}' onclick="${key==='game'?(currentGame?`currentPage='game';renderApp()`:`currentPage='home';renderApp()`):`currentPage='${key}';renderApp()`}">${label}</button>`).join('')}</div>`}
function renderApp(){if(!currentUser){renderLogin();return;}let body='';if(currentPage==='home')body=renderHome();if(currentPage==='game')body=currentGame?renderGame():renderHome();if(currentPage==='bets')body=renderMyBets();if(currentPage==='bank')body=renderBankroll();if(currentPage==='admin')body=renderAdmin();app.innerHTML=renderHeader()+body+renderSlip()+renderNav()}
renderApp();