const GAMES = [
  {
    "id": "jets_dolphins",
    "title": "Jets @ Dolphins",
    "type": "User vs CPU",
    "markets": [
      "Jets +3.5",
      "Dolphins -3.5",
      "Jets ML",
      "Dolphins ML",
      "Over 48.5",
      "Under 48.5",
      "Jets Team Total Over 23.5",
      "Jets Team Total Under 23.5",
      "Dolphins Team Total Over 24.5",
      "Dolphins Team Total Under 24.5",
      "Jaxson Dart 225+ Pass Yards",
      "Jaxson Dart 250+ Pass Yards",
      "Jaxson Dart 275+ Pass Yards",
      "Jaxson Dart Over 1.5 TD",
      "Jaxson Dart Over 2.5 TD",
      "Jaxson Dart Throws INT",
      "Jaxson Dart No INT",
      "Cam Skattebo Anytime TD",
      "Cam Skattebo 60+ Rush",
      "Cam Skattebo 80+ Rush",
      "Elic Ayomanor 70+ Rec",
      "Elic Ayomanor 90+ Rec",
      "Elic Ayomanor Anytime TD",
      "Alt Market 24",
      "Alt Market 25",
      "Alt Market 26",
      "Alt Market 27",
      "Alt Market 28",
      "Alt Market 29",
      "Alt Market 30",
      "Alt Market 31",
      "Alt Market 32",
      "Alt Market 33",
      "Alt Market 34",
      "Alt Market 35",
      "Alt Market 36",
      "Alt Market 37",
      "Alt Market 38",
      "Alt Market 39",
      "Alt Market 40",
      "Alt Market 41",
      "Alt Market 42",
      "Alt Market 43",
      "Alt Market 44",
      "Alt Market 45",
      "Alt Market 46",
      "Alt Market 47",
      "Alt Market 48",
      "Alt Market 49",
      "Alt Market 50",
      "Alt Market 51",
      "Alt Market 52",
      "Alt Market 53",
      "Alt Market 54",
      "Alt Market 55",
      "Alt Market 56",
      "Alt Market 57",
      "Alt Market 58",
      "Alt Market 59",
      "Alt Market 60"
    ]
  },
  {
    "id": "eagles_bucs",
    "title": "Eagles @ Buccaneers",
    "type": "User vs CPU",
    "markets": [
      "Eagles +2.5",
      "Buccaneers -2.5",
      "Eagles ML",
      "Buccaneers ML",
      "Over 50.5",
      "Under 50.5",
      "Bucs Team Total Over 26.5",
      "Bucs Team Total Under 26.5",
      "Trevor Lawrence 250+ Pass",
      "Trevor Lawrence 300+ Pass",
      "Trevor Lawrence 325+ Pass",
      "Trevor Lawrence Over 1.5 TD",
      "Trevor Lawrence Over 2.5 TD",
      "Trevor Lawrence Throws INT",
      "Jonathan Taylor 75+ Rush",
      "Jonathan Taylor 100+ Rush",
      "Jonathan Taylor 125+ Rush",
      "Jonathan Taylor Anytime TD",
      "Jonathan Taylor 2+ TD",
      "DK Metcalf 70+ Rec",
      "DK Metcalf 100+ Rec",
      "DK Metcalf Anytime TD",
      "Alt Market 23",
      "Alt Market 24",
      "Alt Market 25",
      "Alt Market 26",
      "Alt Market 27",
      "Alt Market 28",
      "Alt Market 29",
      "Alt Market 30",
      "Alt Market 31",
      "Alt Market 32",
      "Alt Market 33",
      "Alt Market 34",
      "Alt Market 35",
      "Alt Market 36",
      "Alt Market 37",
      "Alt Market 38",
      "Alt Market 39",
      "Alt Market 40",
      "Alt Market 41",
      "Alt Market 42",
      "Alt Market 43",
      "Alt Market 44",
      "Alt Market 45",
      "Alt Market 46",
      "Alt Market 47",
      "Alt Market 48",
      "Alt Market 49",
      "Alt Market 50",
      "Alt Market 51",
      "Alt Market 52",
      "Alt Market 53",
      "Alt Market 54",
      "Alt Market 55",
      "Alt Market 56",
      "Alt Market 57",
      "Alt Market 58",
      "Alt Market 59",
      "Alt Market 60"
    ]
  },
  {
    "id": "saints_bills",
    "title": "Saints @ Bills",
    "type": "User vs User",
    "markets": [
      "Saints +3.5",
      "Bills -3.5",
      "Saints ML",
      "Bills ML",
      "Over 49.5",
      "Under 49.5",
      "Saints Team Total Over 24.5",
      "Bills Team Total Over 25.5",
      "Lamar Jackson 225+ Pass",
      "Lamar Jackson 275+ Pass",
      "Lamar Jackson Over 1.5 TD",
      "Lamar Jackson Over 2.5 TD",
      "Lamar Jackson 45+ Rush",
      "Lamar Jackson 60+ Rush",
      "Justin Fields 225+ Pass",
      "Justin Fields 275+ Pass",
      "Justin Fields Over 1.5 TD",
      "Trey Benson 70+ Rush",
      "Trey Benson 100+ Rush",
      "Trey Benson Anytime TD",
      "Kyle Pitts Anytime TD",
      "Kyle Pitts 70+ Rec",
      "Alt Market 23",
      "Alt Market 24",
      "Alt Market 25",
      "Alt Market 26",
      "Alt Market 27",
      "Alt Market 28",
      "Alt Market 29",
      "Alt Market 30",
      "Alt Market 31",
      "Alt Market 32",
      "Alt Market 33",
      "Alt Market 34",
      "Alt Market 35",
      "Alt Market 36",
      "Alt Market 37",
      "Alt Market 38",
      "Alt Market 39",
      "Alt Market 40",
      "Alt Market 41",
      "Alt Market 42",
      "Alt Market 43",
      "Alt Market 44",
      "Alt Market 45",
      "Alt Market 46",
      "Alt Market 47",
      "Alt Market 48",
      "Alt Market 49",
      "Alt Market 50",
      "Alt Market 51",
      "Alt Market 52",
      "Alt Market 53",
      "Alt Market 54",
      "Alt Market 55",
      "Alt Market 56",
      "Alt Market 57",
      "Alt Market 58",
      "Alt Market 59",
      "Alt Market 60"
    ]
  },
  {
    "id": "falcons_commanders",
    "title": "Falcons @ Commanders",
    "type": "User vs CPU",
    "markets": [
      "Falcons +2.5",
      "Commanders -2.5",
      "Falcons ML",
      "Commanders ML",
      "Over 47.5",
      "Under 47.5",
      "Falcons Team Total Over 23.5",
      "Falcons Team Total Under 23.5",
      "JJ McCarthy 200+ Pass",
      "JJ McCarthy 250+ Pass",
      "JJ McCarthy Over 1.5 TD",
      "Derrick Henry 70+ Rush",
      "Derrick Henry 100+ Rush",
      "Derrick Henry Anytime TD",
      "Derrick Henry 2+ TD",
      "Falcons Defense 2+ Sacks",
      "Falcons Defense INT",
      "Alt Market 18",
      "Alt Market 19",
      "Alt Market 20",
      "Alt Market 21",
      "Alt Market 22",
      "Alt Market 23",
      "Alt Market 24",
      "Alt Market 25",
      "Alt Market 26",
      "Alt Market 27",
      "Alt Market 28",
      "Alt Market 29",
      "Alt Market 30",
      "Alt Market 31",
      "Alt Market 32",
      "Alt Market 33",
      "Alt Market 34",
      "Alt Market 35",
      "Alt Market 36",
      "Alt Market 37",
      "Alt Market 38",
      "Alt Market 39",
      "Alt Market 40",
      "Alt Market 41",
      "Alt Market 42",
      "Alt Market 43",
      "Alt Market 44",
      "Alt Market 45",
      "Alt Market 46",
      "Alt Market 47",
      "Alt Market 48",
      "Alt Market 49",
      "Alt Market 50",
      "Alt Market 51",
      "Alt Market 52",
      "Alt Market 53",
      "Alt Market 54",
      "Alt Market 55",
      "Alt Market 56",
      "Alt Market 57",
      "Alt Market 58",
      "Alt Market 59",
      "Alt Market 60"
    ]
  }
];